### PR TITLE
#25-IdBug

### LINKED ISSUE #25: User id not assigned properly
image

The user ids were assigned improperly. Instead of each users having their own unique ids, and sharing a static id variable to keep track of how many users have been previously created and prevent id collision, the users all share the same static id.

As a result, all users have the same id, and the id changes whenever a new user is added.

### PR DESCRIPTION
**Pull request by kmarsolais**
Fixed a bug where the id variable would not increment on creation of a user

### CODE REVIEW

**Comment by tommy-josepovic** [comment]
The auto increment still doesn't work. 

Each users must have a non-static variable for their id as well as a static variable to keep track of the number of users to have been created up.

- [ ] Fix the auto-incrementing IDs

I took the liberty of adding a unit that verifies if the features works on the User class.

- [ ] Make the unit test ``ID_Increment_Test`` pass.

If you have issues making the unit test work, you can PM me on Discord, and I'll try to answer ASAP.

**Review by tjosepo — CHANGES_REQUESTED** [review]
The auto increment still doesn't work. 

You need 2 variables:
- One static variable that keeps count of how many objects of that class have been created.
- One non-static variable that holds the value of an object's id.

- [x] Fix the auto-incrementing IDs

I took the liberty of adding a unit that verifies if the features works on the User class.

- [x] Make the unit test ``ID_Increment_Test`` pass.

If you have issues making the unit test work, you can PM me on Discord, and I'll try to answer ASAP.

**Comment by kmarsolais** [comment]
I added more tests for the other classes. This issue can now be closed

**Review by tjosepo — APPROVED** [review]
Looks good.

**Pull request merged**
